test= ("i love video games")
print(test[::-2])
print(test.upper())
print(test.lower())
print(test.strip("i,games"))
print(test.split())

test2= ("i hate", "video games")
print(" playing ".join(test2))
print(test.replace("love","want"))
print(test.startswith("if"))
print(test.endswith("games"))
print(test.capitalize())
print(test.isupper())
print(test.islower())
print(test.title())
print(test.find("hi"))
print(test.count("f"))